import sys
import json
from datetime import datetime, timezone
from types import SimpleNamespace

# Research bot object reference.
research_bot = None

# Global / module-level text buffer
text_buffer = []

session_utc = datetime.now(timezone.utc)
session_formatted_utc = session_utc.strftime("%y%m%d-%H%M%S")

# We have to modify the output callback in order to log the messages generated by bot_agents_boss.
def research_output_callback(text: str):
    text_buffer.append(text)
    print(text, end="", flush=True)

# Same goes to inputs made by the bots.
def research_player_input_callback(text: str):
    global research_bot

    current_utc = datetime.now(timezone.utc)
    formatted_utc = current_utc.strftime("%y%m%d-%H%M%S")

    # First lets empty the buffer from previous messages.
    print(text, end="", flush=True)
    text_to_file = f"_* {formatted_utc}\n" + f"Bot asks: {text}\n"

    answer = input()

    text_to_file = text_to_file + "Player's reply: " + "".join(answer) + "\n"
    research_bot.memory_save(f"log_{session_formatted_utc}", text_to_file, True)

    return answer

def run(bot, short_memory):

    global research_bot
    research_bot = bot

    # Prepare to prompt bot_agents_boss.
    bot_agents_boss = bot.get_linked_bot("agents_boss")
    bot_agents_boss.set_default_output_callback(research_output_callback)
    bot_agents_boss.set_default_prompt_user_input(research_player_input_callback)

    research_bot_ns = SimpleNamespace()
    research_bot_ns.text_buffer = text_buffer
    research_bot_ns.session_formatted_utc = session_formatted_utc
    research_bot.add_to_api("internal_utils", research_bot_ns)

    research_bot.next_node("main", short_memory)

    # Now that we setup minimum requirements, we move to main as starting node.
    research_bot.set_starting_node("main")
